### ISSUE TITLE
Profile Icons broken

### ISSUE THREAD

**Issue by xArtSxze** [schnensch0/zelk#57]
So profile icons are broken. The profile icon is not in it's correct position and it's merged with the username and tag
![SharedScreenshot](https://user-images.githubusercontent.com/114253042/192025455-104c44e3-5e1f-4660-9b13-b25275dd088b.jpg)

Setup: Windows 10

**Comment by Alluseri** [comment]
Can't replicate the issue in question,
<img src="https://cdn.discordapp.com/attachments/853155168170147910/1023378685497180321/unknown.png">
<img src="https://cdn.discordapp.com/attachments/853155168170147910/1023449076362133584/unknown.png">

**Comment by nikosszzz** [comment]
![image](https://user-images.githubusercontent.com/53112175/192138032-df5e3f42-3965-4a12-812c-5495d2c51b61.png)
i have a similar issue, but this only occurs when I open a user's profile to show mutual servers and friends.

**Comment by MIOGMIOG** [comment]
> ![image](https://user-images.githubusercontent.com/53112175/192138032-df5e3f42-3965-4a12-812c-5495d2c51b61.png) i have a similar issue, but this only occurs when I open a user's profile to show mutual servers and friends.

I have same problem as you
![obrazek](https://user-images.githubusercontent.com/82799665/192602296-44517774-49ae-45bd-9777-fa2820ee0cb6.png)

**Comment by griffi-gh** [comment]
yeah same issue since 1.6

**Comment by griffi-gh** [comment]
```css
/* fixes */
.headerTop-3GPUSF {
  padding-top: 2.5rem !important;
}
.avatarWrapper-eenWra.avatarPositionPremium-1zPBq9 {
  transform: translateY(75%) !important;
}
```

rather hacky fix

**Comment by INFINITE31** [comment]
> ```css
> /* fixes */
> .headerTop-3GPUSF {
>   padding-top: 2.5rem !important;
> }
> .avatarWrapper-eenWra.avatarPositionPremium-1zPBq9 {
>   transform: translateY(75%) !important;
> }
> ```
> 
> rather hacky fix

this only works while opening the profile not when you open the mutual servers thing
can you help?
![image](https://user-images.githubusercontent.com/69384561/193231355-95929edb-b999-42fa-9b0f-6473b5bcd262.png)

**Comment by griffi-gh** [comment]
@INFINITE31 
```css
/* fixes */
.headerTop-3GPUSF,
.nameTag-2Nlmsy.nameTag-H6kSJ0 {
  padding-top: 2.5rem !important;
}
.avatarWrapper-eenWra.avatarPositionPremium-1zPBq9,
.wrapper-1VLyxH.avatar-3QF_VA {
  transform: translateY(75%) !important;
}
```
Try this
